name: shopping_list
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  http: 0.13.4
  sizer: 2.0.15
  flutter_svg: 1.1.0
  equatable: 2.0.3
  build_runner: 2.1.11
  badges: 2.0.3
  json_serializable: 6.2.0
  json_annotation: 4.5.0
  formz: 0.4.1
  google_fonts: 3.0.1
  get_storage: 2.0.3
  file_picker: 4.6.1
  intl: 0.17.0
  timeago: 3.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg/
    - assets/icons/
  uses-material-design: true

